apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mysql-pv-claim
        labels:
                application: wordpress
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 4Gi
