apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: wp-pv-claim
        labels:
                application: wordpress
                mode: wordpress-app
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 2Gi
        selector:
                matchLabels:
                        application: wordpress
                        mode: wordpress-app
