apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  labels:
    application: wordpress
    mode: wordpress-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp
