kind: Service			#    --> Defines to create service type object
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  ports:
    - port: 80			#    --> Containers port exposed
      #targetPort: 80		#--> Pods port
  selector:
    application: wordpress		#--> Apply this service to any pods which has the specific label
    mode: wordpress-app
  type: LoadBalancer		 #  --> Specifies the service type i.e. ClusterIP or NodePort
